// app enum
export enum AppTypeEnum {

}

// article enum
export enum ArticleTypeEnum {
    ARTICLE_GET_LIST = 'ARTICLE_GET_LIST',
    ARTICLE_GET_CATEGORY_LIST = 'ARTICLE_GET_CATEGORY_LIST',
    ARTICLE_GET_TAG_LIST = 'ARTICLE_GET_TAG_LIST',
}

// user enum
export enum UserTypeEnum {
    USER_SET_IS_LOGIN = 'USER_SET_IS_LOGIN',
    USER_GET_USER_INFO = 'USER_GET_USER_INFO',
    USER_SET_MODAL_TYPE = 'USER_SET_MODAL_TYPE',
    USER_SET_MODAL_VISIBLE = 'USER_SET_MODAL_VISIBLE',
    USER_GET_UN_READ_MESSAGE_LIST = 'USER_GET_UN_READ_MESSAGE_LIST'
}
